modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "https://github.com/cofh/feedback"
license = "CoFH - Don't Be A Jerk (Learn, Don't Steal)"

[[mods]]
modId = "thermal_horizons"
version = "${file.jarVersion}"
displayName = "Thermal Horizons"
displayURL = "https://teamcofh.com/"
logoFile = "thermal_horizons.png"
credits = "Team CoFH"
authors = "King Lemming"
description = '''
Expanding the world Thermally!

Contains additional biomes and world features.
'''
[[dependencies.thermal_horizons]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_horizons]]
modId = "forge"
mandatory = true
versionRange = "[36.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_horizons]]
modId = "cofh_core"
mandatory = true
versionRange = "[1.4,1.5]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.thermal_horizons]]
modId = "thermal"
mandatory = true
versionRange = "[1.4,1.5]"
ordering = "AFTER"
side = "BOTH"